#### Group Fairness 모델
- FairGNN (Adversarial Learning): 대표
    - FairVGNN (Adversarial Learning)

- EDITS (Edge Rewiring): 대표
    - UGE (Edge Rewiring) : 제외
    - FairEdit (Edge Rewiring)
    - GEAR (Edge Rewiring)

- FairWalk (Rebalancing): 대표
    - CrossWalk (Rebalancing)

- NIFTY (Optimization with Regularization)

- FairGB

In [1]:
import pandas as pd

### ours

In [2]:
file_name ='exp_fairgate'
datasets = ['pokec_z', 'pokec_n', 'german', 'credit', 'recidivism', 'nba', 'income']

df = pd.read_csv(f'./outputs/{file_name}.csv')
df = df[[
    'model', 'dataset',
    'acc_mean', 'acc_std', 'roc_auc_mean', 'roc_auc_std',
    'dp_mean', 'dp_std', 'eo_mean', 'eo_std', 
    'time_sec_mean', 'time_sec_std']]

# pockec_z: 0
# pokec_n: 1
# german: 2
# credit: 3
# recidivism: 4

# df[df.dataset == datasets[6]]
df

,model,dataset,acc_mean,acc_std,roc_auc_mean,roc_auc_std,dp_mean,dp_std,eo_mean,eo_std,time_sec_mean,time_sec_std
0,FairGate,pokec_z,0.6918,0.0053,0.7490,0.0033,0.0092,0.0043,0.0053,0.0055,17.60,1.8193
1,FairGate,pokec_n,0.6938,0.0044,0.7282,0.0032,0.0577,0.0300,0.0734,0.0440,14.74,4.8614
2,FairGate,credit,0.7778,0.0035,0.6766,0.0259,0.0193,0.0130,0.0114,0.0091,47.04,4.7836
3,FairGate,german,0.6576,0.0268,0.6194,0.0202,0.0708,0.0432,0.0609,0.0288,15.84,2.8919
4,FairGate,recidivism,0.8528,0.0080,0.8867,0.0062,0.0686,0.0040,0.0450,0.0089,24.48,13.0085
5,FairGate,nba,0.7239,0.0216,0.7802,0.0032,0.0405,0.0204,0.0470,0.0446,5.46,5.6297
6,FairGate,income,0.8088,0.0039,0.7703,0.0069,0.0256,0.0060,0.0232,0.0090,56.90,12.6129

In [3]:
file_name ='exp_pokec_gender'
datasets = ['pokec_z', 'pokec_n', 'german', 'credit', 'recidivism', 'nba', 'income']

df = pd.read_csv(f'./outputs/{file_name}.csv')
df = df[[
    'model', 'dataset',
    'acc_mean', 'acc_std', 'roc_auc_mean', 'roc_auc_std',
    'dp_mean', 'dp_std', 'eo_mean', 'eo_std', 
    'time_sec_mean', 'time_sec_std']]

# pockec_z: 0
# pokec_n: 1
# german: 2
# credit: 3
# recidivism: 4

# df[df.dataset == datasets[6]]
df

,model,dataset,acc_mean,acc_std,roc_auc_mean,roc_auc_std,dp_mean,dp_std,eo_mean,eo_std,time_sec_mean,time_sec_std
0,FairGate,pokec_z_g,0.6892,0.0056,0.7559,0.0032,0.0699,0.0293,0.0176,0.0184,40.08,15.4941
1,FairGate,pokec_n_g,0.6880,0.0050,0.7287,0.0067,0.0271,0.0080,0.0809,0.0082,39.00,0.7416
2,NIFTY,pokec_z_g,0.6531,0.0267,0.6523,0.0286,0.0396,0.0121,0.0599,0.0211,45.20,8.2985
3,NIFTY,pokec_n_g,0.6654,0.0131,0.6614,0.0130,0.0754,0.0204,0.1328,0.0203,56.12,2.0969
4,FairGNN,pokec_z_g,0.6761,0.0038,0.6809,0.0026,0.0592,0.0182,0.0766,0.0226,16.80,0.5431
5,FairGNN,pokec_n_g,0.6836,0.0053,0.6797,0.0047,0.0780,0.0071,0.1341,0.0123,16.80,0.4301
6,FairVGNN,pokec_z_g,0.6625,0.0052,0.7393,0.0048,0.0127,0.0115,0.0380,0.0116,1661.62,303.3205

### baselines

In [12]:
file_name ='exp_baselines'
datasets = ['pokec_z', 'pokec_n', 'german', 'credit', 'recidivism', 'nba', 'income']

df_v2 = pd.read_csv(f'./outputs/{file_name}.csv')
df_v2 = df_v2[[
    'model', 'dataset',
    'acc_mean', 
    'acc_std', 
    'roc_auc_mean',
    'roc_auc_std',
    'dp_mean',
    'dp_std',
    'eo_mean', 
    'eo_std', 
    # 'time_sec_mean', 
    # 'time_sec_std'
]]

model_order = ['FairGNN', 'FairVGNN', 'EDITS', 'FairEdit', 
               'FairWalk', 'CrossWalk', 'FairGB', 'NIFTY', 'FairGT']

filtered_df = df_v2[(df_v2.dataset == 'credit') & (df_v2.model != 'GNN')].copy()

filtered_df['model'] = pd.Categorical(
    filtered_df['model'],
    categories=model_order,
    ordered=True
)
filtered_df.sort_values('model')

# df_v2[df_v2.model == 'CrossWalk']

,model,dataset,acc_mean,acc_std,roc_auc_mean,roc_auc_std,dp_mean,dp_std,eo_mean,eo_std
15,FairGNN,credit,0.7873,0.0029,0.6029,0.0070,0.0867,0.0399,0.0461,0.0363
20,FairVGNN,credit,0.7372,0.0061,0.7147,0.0036,0.1680,0.0524,0.1474,0.0549
53,EDITS,credit,0.7234,0.0002,0.6947,0.0001,0.2700,0.0004,0.2687,0.0006
25,FairWalk,credit,0.7532,0.0050,0.6032,0.0059,0.0855,0.0155,0.0677,0.0154
30,CrossWalk,credit,0.7799,0.0022,0.6095,0.0052,0.0872,0.0158,0.0642,0.0140
6,FairGB,credit,0.7512,0.0463,0.7226,0.0176,0.0274,0.0257,0.0120,0.0122
3,NIFTY,credit,0.7359,0.0651,0.6666,0.0244,0.1843,0.0363,0.1541,0.0492

### gcn

In [63]:
file_name ='exp_gcn'
df_ab = pd.read_csv(f'./outputs/{file_name}.csv')
# df_ab = df_ab[df_ab.dataset == 'recidivism']
df_ab = df_ab.drop(['stage_label', 'run', 'seed'], axis=1)

df_ab.groupby(['dataset', 'stage']).agg(['mean', 'std']).round(4)

                     acc         roc_auc              f1              dp  \
                    mean     std    mean     std    mean     std    mean
dataset    stage
credit     A0     0.7468  0.0018  0.7423  0.0022  0.8283  0.0016  0.1436
german     A0     0.6120  0.0049  0.6459  0.0082  0.6768  0.0063  0.4957
income     A0     0.7994  0.0007  0.7868  0.0019  0.5302  0.0058  0.1841
nba        A0     0.7371  0.0152  0.7803  0.0027  0.7652  0.0220  0.0396
pokec_n    A0     0.6904  0.0028  0.7368  0.0015  0.6514  0.0042  0.1058
pokec_n_g  A0     0.6719  0.0108  0.7282  0.0070  0.6637  0.0053  0.0136
pokec_z    A0     0.6878  0.0024  0.7581  0.0012  0.7021  0.0031  0.0647
pokec_z_g  A0     0.6907  0.0023  0.7566  0.0022  0.6940  0.0055  0.1070
recidivism A0     0.8504  0.0038  0.8916  0.0012  0.7977  0.0039  0.0755

                              eo         time_sec
                     std    mean     std     mean     std
dataset    stage
credit     A0     0.0030  0.1200  0.0037    16.02  2.8700
german     A0     0.0116  0.5334  0.0103     6.06  2.7646
income     A0     0.0043  0.2586  0.0089    14.74  2.4172
nba        A0     0.0118  0.0528  0.0254     9.42  1.5595
pokec_n    A0     0.0081  0.1252  0.0165     7.34  0.2302
pokec_n_g  A0     0.0091  0.0501  0.0148    13.20  3.5057
pokec_z    A0     0.0101  0.0515  0.0097     8.34  0.5857
pokec_z_g  A0     0.0088  0.0471  0.0066     8.70  0.7550
recidivism A0     0.0030  0.0422  0.0034    10.80  2.6038

### ablation

In [22]:
file_name ='exp_a3_ablation'
df_ab = pd.read_csv(f'./outputs/{file_name}.csv')
# df_ab = df_ab[df_ab.dataset == 'recidivism']
df_ab = df_ab.drop(['stage_label', 'run', 'seed'], axis=1)

df_ab.groupby(['dataset', 'stage']).agg(['mean']).round(4)

                     acc roc_auc      f1      dp      eo time_sec
                    mean    mean    mean    mean    mean     mean
dataset    stage
credit     A3     0.7761  0.6825  0.8641  0.0362  0.0145    68.86
german     A3     0.6448  0.6327  0.7568  0.1000  0.1193    28.02
pokec_n    A3     0.6891  0.7300  0.6385  0.0949  0.1141    39.82
pokec_n_g  A3     0.6838  0.7294  0.6535  0.0184  0.0703    33.70
pokec_z    A3     0.6931  0.7483  0.6871  0.0194  0.0187    59.90
pokec_z_g  A3     0.6920  0.7554  0.6811  0.0581  0.0071    64.24
recidivism A3     0.8515  0.8837  0.7931  0.0687  0.0441    47.74

In [23]:
file_name ='exp_a4_ablation'
df_ab = pd.read_csv(f'./outputs/{file_name}.csv')
# df_ab = df_ab[df_ab.dataset == 'recidivism']
df_ab = df_ab.drop(['stage_label', 'run', 'seed'], axis=1)

df_ab.groupby(['dataset', 'stage']).agg(['mean']).round(4)

                     acc roc_auc      f1      dp      eo time_sec
                    mean    mean    mean    mean    mean     mean
dataset    stage
credit     A4     0.7752  0.6901  0.8622  0.0253  0.0123    82.26
german     A4     0.6488  0.6296  0.7566  0.0686  0.0819    26.26
pokec_n    A4     0.6900  0.7249  0.6304  0.0682  0.0915    63.52
pokec_n_g  A4     0.6855  0.7288  0.6559  0.0182  0.0668    24.60
pokec_z    A4     0.6924  0.7487  0.6849  0.0095  0.0089    90.10
pokec_z_g  A4     0.6885  0.7521  0.6783  0.0572  0.0084    54.86
recidivism A4     0.8537  0.8851  0.7955  0.0715  0.0504    38.88